### ISSUE TITLE
installation: no match for ‘operator==’

### ISSUE THREAD

**Issue by lurebgi** [bioinfomaticsCSU/BOSS#1]
Hi,

I had an issue of installing it:
scaffoldgraph.cpp: In function ‘ContigSet* GetContigSet(char*, long int&)’:
scaffoldgraph.cpp:307:12: error: no match for ‘operator==’ (operand types are ‘std::ifstream {aka std::basic_ifstream<char>}’ and ‘long int’)
     if(icin==NULL){
            ^
scaffoldgraph.cpp:307:12: note: candidate: operator==(int, long int) <built-in>
scaffoldgraph.cpp:307:12: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘int’
In file included from include/api/SamProgramChain.h:14:0,
                 from include/api/SamHeader.h:14,
                 from include/api/BamReader.h:16,
                 from include/api/BamMultiReader.h:14,
                 from scaffoldgraph.h:13,
                 from scaffoldgraph.cpp:14:

Any clue of how to fix that?

Thanks!

**Comment by bioinfomaticsCSU** [comment]
Hi,

We test BOSS using gcc4.6.3 on Ubuntu. When using GCC6, this problem will happen. Now, we change the source code. Please download the newes BOSS. If you have any problem when using BOSS, please let us know. 

Thanks!

**Comment by lurebgi** [comment]
g++ -c main.cpp -lm -ldl -I include/ -L lib/ -lbamtools -std=gnu++98
g++ -c scaffoldgraph.cpp -lm -ldl -I include/ -L lib/ -lbamtools
-std=gnu++98
g++ -c scaffolding.cpp -lm -ldl -I include/ -L lib/ -lbamtools -std=gnu++98
g++ -o boss main.o scaffoldgraph.o scaffolding.o ./lp/liblpsolve55.a -lm
-ldl -I include/ -L lib/ -lbamtools -std=gnu++98
/usr/bin/ld: cannot find -lbamtools
collect2: error: ld returned 1 exit status
makefile:7: recipe for target 'boss' failed
make: *** [boss] Error 1

**Comment by bioinfomaticsCSU** [comment]
Hi,

Please download the newest BOSS. 
Add the path (the directory of BOSS) to the enviroment variable LD_LIBRARY_PATH. Then type "make all".

In addition, we upload the binary file "boss", you can use the command "boss" for running.

If you have any problem, please let us know.

Thanks

**Comment by lurebgi** [comment]
Thanks, the binary file works. One kind remind: one should create a soft link to libbamtools.so as libbamtools.so.2.3.0

**Comment by bioinfomaticsCSU** [comment]
Thanks!

**Comment by lurebgi** [comment]
Hello, it reported an error message "Open File Wrong!" when I used the binary file provided. Could you please check that?
Thanks!
Luohao

**Comment by lurebgi** [comment]
solved by linking to bamtools.so file of latest version under apps which allowed then to recompile it

**Comment by pawelosipowski** [comment]
Hi I have the same issue: "Open File Wrong!". How can I solve it step by step?

**Comment by lurebgi** [comment]
in scaffoldgraph.cpp, on the line 307 you can try changing 'if(icin){‘ into 'if(!icin){‘ 

by the way, I got an segmental fault, so in the end this tool did work out for me.

**Comment by bioinfomaticsCSU** [comment]
Hi, we update readme.md, please install BOSS again.
