### ISSUE TITLE
"Open File Wrong!"

### ISSUE THREAD

**Issue by pawelosipowski** [bioinfomaticsCSU/BOSS#3]
How can I solve it step by step?

**Comment by bioinfomaticsCSU** [comment]
Hi, we update one bug, please download BOSS again and compile it.
Thanks very much!

**Comment by bioinfomaticsCSU** [comment]
Hi, we update readme.md, please install BOSS again.

**Comment by pawelosipowski** [comment]
Now is OK! Thanks
